# Generated by Django 6.1.1 on 2026-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('premises', 'Ordering at Premises'), ('collection', 'Order for Collection'), ('delivery', 'Delivery')], max_length=20),
        ),
    ]
