# Generated by Django 6.1.1 on 2026-10-01 13:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_delivery_address_alter_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_radius_km', models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('service_percentage', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('business_percentage', models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=5)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pricing', to='orders.shop')),
            ],
        ),
    ]
