# Generated by Django 6.1.1 on 2026-10-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_deliverypricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='orders.deliverypricing')),
            ],
            options={
                'ordering': ['max_distance_km'],
            },
        ),
    ]
