# Generated by Django 6.1.1 on 2026-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_deliveryrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Collection'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Collection'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
