# Generated by Django 6.1.1 on 2026-10-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('online', 'Online')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Delivery'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('braaiing', 'Braaiing'), ('ready', 'Ready for Delivery'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
