# Generated by Django 6.1.1 on 2026-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_customer_latitude_order_customer_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='braai_master',
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_colour',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_make_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_registration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('ready', 'Ready for Delivery'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Order Received'), ('preparing', 'Preparing Order'), ('ready', 'Ready for Delivery'), ('driver_assigned', 'Driver Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('collected', 'Completed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.DeleteModel(
            name='BraaiMaster',
        ),
    ]
