# Generated by Django 6.1.1 on 2026-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_customerprofile_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='banking_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
