# Generated by Django 6.1.1 on 2026-10-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_driver_account_holder_name_driver_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='airxpress_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
