# Generated by Django 6.1.1 on 2026-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_driver_airxpress_verified_driver_driver_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='physical_address',
            field=models.TextField(blank=True, default='', help_text='Driver physical address obtained from banking information.'),
        ),
        migrations.AddField(
            model_name='driver',
            name='physical_address',
            field=models.TextField(blank=True, default='', help_text='Driver physical address obtained from banking information.'),
        ),
    ]
